---
date: "`r lubridate::now()`"
title: Curriculum Vitae
---

## PERSONAL INFORMATION

Name: Frederick Joseph Boehm, III    
Citizenship: U.S.A.    
Address: 1220 Medical Sciences Center    
         1300 University Avenue    
         Madison, WI 53715    
         U.S.A.    
Email Address: <frederick.boehm@gmail.com>


## EDUCATION

Ph.D. in Statistics, University of Wisconsin-Madison, 2018 (anticipated)  
M.D., University of Wisconsin-Madison, 2007  
M.S. in Population Health Sciences, University of Wisconsin-Madison, 2007  
B.S. in Chemistry, Mathematics, and Biochemistry, University of Wisconsin-Madison, 2001  

## EMPLOYMENT

[University of Wisconsin-Madison Molecular and Environmental Toxicology Center](http://metc.wisc.edu), Postdoctoral Trainee, 2012-2014    
[University of Wisconsin-Madison Value-Added Research Center](http://varc.wceruw.org), Assistant Researcher, 2011  
[University of Washington Department of Biostatistics](http://www.biostat.washington.edu), Senior Fellow, 2007-2009  

## AWARDS & HONORS

IRES Research Ethics Fellowship, University of Wisconsin-Madison, 2013-2014    
[New Arts Venture Challenge Award](https://artsinstitute.wisc.edu/navc.htm#acc-panel-481) for [Victorian Eyes art exhibition](http://victorianeyes.com), University of Wisconsin-Madison, 2013   
[Medical Student Research Training Fellowship](http://www.hhmi.org/news/medical-dental-students-taste-life-research-scientists), Howard Hughes Medical Institute, 2006 (declined due to security concerns in Haiti)    
Shapiro Award for research with Partners In Health, University of Wisconsin-Madison, 2004    
Department of Family Medicine LOCUS stipend for research with Partners In Health, University of Wisconsin-Madison, 2004    
[Graduate Research Fellowship](https://catalog.data.gov/dataset/nsf-graduate-research-fellowship-program-award-recipients-2001), National Science Foundation, 2001    
Meyerhoff Excellence Award, University of Wisconsin-Madison, 2001    
University Book Store Award for Outstanding Undergraduate Thesis, University of Wisconsin-Madison, 2001    
Department of Chemistry Edward Panek Memorial Scholarship, University of Wisconsin-Madison, 2000    
[Hilldale Undergraduate Research Fellowship](http://news.wisc.edu/hilldale-undergraduate-awards-listed/), University of Wisconsin-Madison, 1999    
Wisconsin Idea Fellowhsip for the Salvation Army Learning Center, University of Wisconsin-Madison, 1999    
Ralph B. Abrams Scholarship, University of Wisconsin-Madison, 1999     
Margaret and Allard Smith Scholarship, University of Wisconsin-Madison, 1998     
Department of Chemistry Summer Research Scholarship, University of Wisconsin-Madison, 1998    
Dean's List, University of Wisconsin-Madison, Spring 1997, Spring 1998 to Spring 2001    
College of Letters & Science Honors Program, University of Wisconsin-Madison, 1996 to 2001    
Wisconsin Academic Excellence Scholarship, University of Wisconsin-Madison, 1996 to 2000    


## TEACHING EXPERIENCE

### Formal Courses    

The College Classroom: How to teach inclusively for educating a diverse nation   
Co-facilitator, Spring 2017, University of Wisconsin-Madison
Introductory statistics for biologists    
Lecturer student assistant (Instructor of record), Fall 2016, University of Wisconsin-Madison    
Data science    
Guest lecturer on topic models, Fall 2016, University of Wisconsin-Madison    
Data science    
Teaching assistant, Fall 2016, University of Wisconsin-Madison    
Introductory statistics for engineers    
Lecturer student assistant (Instructor of record), Spring 2014, Fall 2014, Spring 2015, Fall 2015, Spring 2016, University of Wisconsin-Madison    
Introductory statistics    
Lecturer student assistant (Instructor of record), Summer 2015, University of Wisconsin-Madison    
Introduction to biostatistics    
Teaching assistant, Fall 2009, Winter 2010, University of Washington
Biostatistics 511    
Teaching assistant, Summer 2008, University of Washington    
Introductory organic chemistry
Graduate student instructor, Fall 2001, University of California-Berkeley

### Short Courses & Workshops




## PUBLISHED WORKS






