baseurl = "https://fredboehm.us/"
title = "Frederick Boehm's Website"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "fredsblog2" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-46757486-5" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Frederick Boehm"
    bio = "Frederick Boehm is a biostatistics researcher and teacher who lives in Madison, Wisconsin."
    avatar = "img/boehm.png"


[Params]
    subtitle = "" # Subtitle of your site
    description = " " # Description of your site
    opengraph = true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)