baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Frederick Boehm's Website"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-46757486-5"
disqusShortname = "fredsblog2"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]




[permalinks]
    post = "/:year/:month/:day/:slug/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Curriculum Vitae"
    url = "/curriculum-vitae/"
    weight = 3

[params]
    description = "Frederick Boehm's Website."
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

