---
title: Understanding REML for estimating variance components
author: Frederick Boehm
date: '`r lubridate::now()`'
draft: 'true'
bibliography: blog.bib
slug: understanding-reml-for-estimating-variance-components
categories:
  - statistics
tags:
  - Linear mixed effects models
  - Variance components
---

## Overview

I used much of the summer of 2017 to study linear mixed effects models. I'm writing this blog post to document my experience. Perhaps readers will find it useful in designing their study plans for mixed models.

I found particularly useful Sections 8.4 and 8.5 of @wakefield2013bayesian. The author describes in detail a general framework for linear mixed models before venturing into likelihood-based inference for these models. Particularly appealing to me, and differing from works of many others, is the emphasis of @wakefield2013bayesian on being explicit about conditioning. For instance, in page on 359, he describes a two-stage linear mixed model (LMM) by stating that the first stage involves a response model that is *conditional* on the random effects. I can't recall other authors whose notation and language so clearly explained this and other instances of conditioning in discussions of LMMs.



## Literature cited

