baseurl = "https://fboehm.us/"
languageCode = "en-us"
title = "Frederick Boehm's Website"
# Enable comments by entering your Disqus shortname
disqusShortname = "fredsblog2"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-46757486-5"
# Define the number of posts per site
paginate = 10
theme = "hugo-theme-wave"

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you're
    location = "Madison, Wisconsin"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [hugo-theme-arch](https://github.com/syui/hugo-theme-arch)."

    # Format dates with Go's time formating
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"
    weight = 1

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"
    weight = 2

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"
    weight = 3


# Enter a link for the follow button on the left
[params.profile]
    follow_button = ""


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "fboehm"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "fredboehm"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "fred.boehm.1"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "FredBoehm128"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

